### ISSUE TITLE
Uploading shapefile - says NAME column is missing when it is not. 

### ISSUE THREAD

**Issue by TimKasoar-NIRAS** [HiDef-Aerial-Surveying/mCRM#3]
When attempting to upload a shapefile, I get an error "'NAME' column is not available in the shapefile, please ensure unique names are specified in a NAME field".
Obviously I have ensured there is a NAME field in the shapefile so not sure what is causing the error.

**Comment by grwhumphries** [comment]
Have added a check here for this and it should be working now.

**Comment by TimKasoar-NIRAS** [comment]
Hi Grant, I'm still getting the same problem when using this tool online. I would note that it works fine loading in the exact same shapefile when running the app locally.
